version: '3.8'

services:
  mongodb:
    image: mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - D:\Alejandro\Documents\Universidad\Tercero\BD\MongoDB:/data/db
    networks:
      - my-network

  artemis-activemq:
    image: apache/activemq-artemis
    ports:
      - "61616:61616"
      - "8161:8161"
    networks:
      - my-network

  cleaner:
    image: mmdezr/inverted_index:cleaner
    depends_on:
      - artemis-activemq
    networks:
      - my-network
    volumes:
      - D:\Alejandro\Desktop\datalake:/datalake

  crawler:
    image: mmdezr/inverted_index:crawler
    depends_on:
      - artemis-activemq
    networks:
      - my-network
    volumes:
      - D:\Alejandro\Desktop\datalake:/datalake

  datamart-builder-jar:
    image: mmdezr/inverted_index:datamart-builder
    depends_on:
      - mongodb
      - artemis-activemq
    networks:
      - my-network
    volumes:
      - D:\Alejandro\Desktop\datalake:/datalake

  api-jar:
    image: mmdezr/inverted_index:api-jar
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - my-network
  


networks:
  my-network:
